# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ishan Marikar
tagline:          Code Mechanic
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Ishan Marikar
  url:            https://twitter.com/ishanmarikar
  email:          ishan.marikar@outlook.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
